name: Test macbook
favicon: null
layout_spectrum: 0.17793225427158177
typography_spectrum: 0.09468301269225776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.15161217120476067
  lightness: 0.4202071577310562
  saturation: 0.29352022567763925
  rhythmicContrast: 0.5727977955248207
purpose: []
