analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9179105
  brandStrength: 0.2103545
  lightness: 0.09748134
  brandColors:
    - '#383732'
    - '#77797E'
    - '#776E01'
    - '#FAA44B'
    - '#CFCFBD'
  rhythmicContrast: 0.7346082
typography_spectrum: 0.09468301269225776
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.1779322542715818
favicon: null
name: Test macbook
